config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :users do
    collection do
      get 'my-profile', to: 'users#my_profile'
      post :update_pictures
    end
  end

  resources :projects, only: [:index, :create]
  resources :jobs, only: [:index]

  resources :saved_items, only: [] do
    collection do
      post ':item_type/:item_id', action: :toggle
    end
  end

  resources :likes, only: [] do
    post :toggle_like_dislike, on: :collection
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :feedback_by, class_name: :User
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :job_category
  belongs_to :uploader, class_name: 'User'

  has_many :job_skills
  has_many :skills, through: :job_skills

  has_many :saved_items, as: :item
  has_many :likes, as: :likeable

  has_many :comments, as: :commentable
  has_many :views, as: :viewable

  validates :title, :description, presence: true

  enum job_type: { 'hourly': 'hourly', 'part_time': 'part_time', 'full_time': 'full_time' }
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
end

app/models/job_skill.rb
class JobSkill < ApplicationRecord
  belongs_to :job
  belongs_to :skill
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  belongs_to :uploader, class_name: :User

  has_many :project_skills
  has_many :skills, through: :project_skills

  has_many :saved_items, as: :item
  has_many :likes, as: :likeable

  has_many :comments, as: :commentable
  has_many :views, as: :viewable

  validates :title, :description, presence: true
end

app/models/project_skill.rb
class ProjectSkill < ApplicationRecord
  belongs_to :project
  belongs_to :skill
end

app/models/saved_item.rb
class SavedItem < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :project_skills
  has_many :projects, through: :project_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2, :linkedin]

  has_one_attached :profile_picture

  has_many :saved_items
  has_many :saved_projects, -> { where(item_type: :Project) }, class_name: :SavedItem

  has_many :likes
  has_many :liked_projects, through: :likes, source: :likeable, source_type: 'Project'

  has_many :views

  has_many :feedbacks, as: :feedbackable

  # Followers
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  # Followings
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followings, through: :following_relationships, source: :following

  has_one_attached :profile_picture
  has_one_attached :profile_picture_banner

  def rating
    self.feedbacks.average(:rating) || 0
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(first_name: data['first_name'],
        last_name: data['last_name'],
        email: data['email'],
        password: Devise.friendly_token[0,20],
        provider: 'google'
      )
    end
    user
  end

  def self.connect_to_linkedin(auth, signed_in_resource=nil) 
    user = User.where(provider: 'linkedin', email: auth.info.email).first
    if user
      return user 
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user 
        return registered_user 
      else 
        user = User.create(first_name: auth.info.first_name, provider: 'linkedin', uid:auth.uid, email:auth.info.email, password:Devise.friendly_token[0,20])
      end 
    end 
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :viewable, polymorphic: true
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #skip_before_action :authenticate_user!

  def index
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    filters = params[:filters].present? ? JSON.parse(params[:filters]) : {}
    @jobs = JobFilterService.call(params[:q], filters, Job.includes(:skills, :job_category).all).order(created_at: :asc)

    respond_to do |format|
      format.html # Render HTML by default
      format.js   # Render JavaScript response for AJAX requests
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_saved_item?(item_type, item_id)
    return false unless current_user

    current_user.saved_items.find_by(item_type: item_type.classify, item_id: item_id).present?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_picture_url
    if current_user.profile_picture.attached?
      url_for(current_user.profile_picture)
    else
      asset_path('resources/user-pro-img.png')
    end
  end

  def profile_picture_banner_url
    if current_user.profile_picture_banner.attached?
      url_for(current_user.profile_picture_banner)
    else
      asset_path('resources/cover-img.jpg')
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Workwise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  </head>

  <body>
  	<div class="wrapper">	
      <%= render partial: 'shared/header' %>
      <%= yield %>
      <%= render partial: 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="footy-sec mn no-margin">
    <div class="container">
      <ul>
        <li><a href="help-center.html" title="">Help Center</a></li>
        <li><a href="about.html" title="">About</a></li>
        <li><a href="#" title="">Privacy Policy</a></li>
        <li><a href="#" title="">Community Guidelines</a></li>
        <li><a href="#" title="">Cookies Policy</a></li>
        <li><a href="#" title="">Career</a></li>
        <li><a href="forum.html" title="">Forum</a></li>
        <li><a href="#" title="">Language</a></li>
        <li><a href="#" title="">Copyright Policy</a></li>
      </ul>
      <p><img src="images/copy-icon2.png" alt="">Copyright 2019</p>
      <img class="fl-rgt" src="images/logo2.png" alt="">
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="header-data">
      <div class="logo">
        <a href="<%= root_path %>" title=""><%= image_tag("logo.png", alt: "Logo") %></a>
      </div>
      <div class="search-bar">
        <form>
          <input type="text" name="search" placeholder="Search...">
          <button type="submit"><i class="la la-search"></i></button>
        </form>
      </div><!--search-bar end-->
      <nav>
        <ul>
          <li>
            <a href="<%= root_path %>" title="">
              <span><%= image_tag("icon1.png", alt: "Logo") %></span>
              Home
            </a>
          </li>
          <li>
            <a href="companies.html" title="">
              <span><%= image_tag("icon2.png", alt: "Logo") %></span>
              Companies
            </a>
            <ul>
              <li><a href="companies.html" title="">Companies</a></li>
              <li><a href="company-profile.html" title="">Company Profile</a></li>
            </ul>
          </li>
          <li>
            <a href="<%= projects_path %>" title="">
              <span><%= image_tag("icon3.png", alt: "Logo") %></span>
              Projects
            </a>
          </li>
          <li>
            <a href="profiles.html" title="">
              <span><%= image_tag("icon4.png", alt: "Logo") %></span>
              Profiles
            </a>
            <ul>
              <li><a href="user-profile" title="">User Profile</a></li>
              <li><a href="users/my-profile" title="">My Profile</a></li>
            </ul>
          </li>
          <li>
            <a href="<%= jobs_path %>" title="">
              <span><%= image_tag("icon5.png", alt: "Logo") %></span>
              Jobs
            </a>
          </li>
          <% if user_signed_in? %>
            <li>
              <a href="#" title="" class="not-box-openm">
                <span><%= image_tag("icon6.png", alt: "Logo") %></span>
                Messages
              </a>
              <div class="notification-box msg" id="message">
                <div class="nt-title">
                  <h4>Setting</h4>
                  <a href="#" title="">Clear all</a>
                </div>
                <div class="nott-list">
                  <div class="notfication-details">
                      <div class="noty-user-img">
                        <%= image_tag("resources/ny-img1.png", alt: "") %>
                      </div>
                      <div class="notification-info">
                        <h3><a href="messages.html" title="">Jassica William</a> </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</p>
                        <span>2 min ago</span>
                      </div><!--notification-info -->
                    </div>
                    <div class="notfication-details">
                      <div class="noty-user-img">
                      <%= image_tag("resources/ny-img2.png", alt: "") %>
                      </div>
                      <div class="notification-info">
                        <h3><a href="messages.html" title="">Jassica William</a></h3>
                        <p>Lorem ipsum dolor sit amet.</p>
                        <span>2 min ago</span>
                      </div><!--notification-info -->
                    </div>
                    <div class="notfication-details">
                      <div class="noty-user-img">
                        <%= image_tag("resources/ny-img3.png", alt: "") %>
                      </div>
                      <div class="notification-info">
                        <h3><a href="messages.html" title="">Jassica William</a></h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo incididunt ut labore et dolore magna aliqua.</p>
                        <span>2 min ago</span>
                      </div><!--notification-info -->
                    </div>
                    <div class="view-all-nots">
                      <a href="messages.html" title="">View All Messsages</a>
                    </div>
                </div><!--nott-list end-->
              </div><!--notification-box end-->
            </li>
            <%= render partial: 'shared/header/notification' %>
          <% else %>
            <%= render partial: 'shared/header/notification' %>
            <li>
              <a href="<%= new_user_session_path %>" title="">
                <span><%= image_tag("custom/auth.png", alt: "Logo") %></span>
                SignIn/Register
              </a>
            </li>
          <% end %>
        </ul>
      </nav><!--nav end-->
      <div class="menu-btn">
        <a href="#" title=""><i class="fa fa-bars" aria-hidden="true"></i></a>
      </div><!--menu-btn end-->
      <% if user_signed_in? %>
        <div class="user-account">
          <div class="user-info">
            <%= image_tag("resources/user.png", alt: "") %>
            <a href="#" title="">John</a>
            <i class="la la-sort-down"></i>
          </div>
          <div class="user-account-settingss" id="users">
            <h3>Online Status</h3>
            <ul class="on-off-status">
              <li>
                <div class="fgt-sec">
                  <input type="radio" name="cc" id="c5">
                  <label n. css file will be available to your entire afor="c5">
                    <span></span>
                  </label>
                  <small>Online</small>
                </div>
              </li>
              <li>
                <div class="fgt-sec">
                  <input type="radio" name="cc" id="c6">
                  <label for="c6">
                    <span></span>
                  </label>
                  <small>Offline</small>
                </div>
              </li>
            </ul>
            <h3>Custom Status</h3>
            <div class="search_form">
              <form>
                <input type="text" name="search">
                <button type="submit">Ok</button>
              </form>
            </div><!--search_form end-->
            <h3>Setting</h3>
            <ul class="us-links">
              <li><a href="profile-account-setting.html" title="">Account Setting</a></li>
              <li><a href="#" title="">Privacy</a></li>
              <li><a href="#" title="">Faqs</a></li>
              <li><a href="#" title="">Terms & Conditions</a></li>
            </ul>
            <h3 class="tc">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, title: "Logout" %>
            </h3>
          </div><!--user-account-settingss end-->
        </div>
      <% end %>
    </div><!--header-data end-->
  </div>
</header><!--header end-->	

app/views/shared/header/_notification.html.erb
<li>
  <a href="#" title="" class="not-box-open">
    <span><%= image_tag("icon7.png", alt: "") %></span>
    Notification
  </a>
  <div class="notification-box noti" id="notification">
    <div class="nt-title">
      <h4>Setting</h4>
      <a href="#" title="">Clear all</a>
    </div>
    <div class="nott-list">
      <div class="notfication-details">
          <div class="noty-user-img">
            <%= image_tag("resources/ny-img1.png", alt: "") %>
          </div>
          <div class="notification-info">
            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
            <span>2 min ago</span>
          </div><!--notification-info -->
        </div>
        <div class="notfication-details">
          <div class="noty-user-img">
            <%= image_tag("resources/ny-img2.png", alt: "") %>
          </div>
          <div class="notification-info">
            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
            <span>2 min ago</span>
          </div><!--notification-info -->
        </div>
        <div class="notfication-details">
          <div class="noty-user-img">
          <%= image_tag("resources/ny-img3.png", alt: "") %>
          </div>
          <div class="notification-info">
            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
            <span>2 min ago</span>
          </div><!--notification-info -->
        </div>
        <div class="notfication-details">
          <div class="noty-user-img">
            <%= image_tag("resources/ny-img2.png", alt: "") %>
          </div>
          <div class="notification-info">
            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
            <span>2 min ago</span>
          </div><!--notification-info -->
        </div>
        <div class="view-all-nots">
          <a href="#" title="">View All Notification</a>
        </div>
    </div><!--nott-list end-->
  </div><!--notification-box end-->
</li>